---
- hosts: centos
  become: true
  vars_files:
    - /home/lakshmi/ansible-control/vars.yml
  tasks:
    - name: add several users
      user: 
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
      with_items: "{{ user_details }}"
