---
- name: Start and Enable httpd service
  service: name=httpd state=restarted enabled=yes
- name: start and enable firewalld for http service
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
